<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('YouSelfie ' . $this->translate('- Compartilhe momentos com seus amigos'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/jquery.maskedinput.min.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-ui.js'))
                ->prependFile($this->basePath('js/main.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/jquery.js'))
        ;
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header ">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>"/>&nbsp;</a>
                </div>
            </div>
        </nav>
        <div class="container">

            <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                <div class="alert alert-success">
                    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong><?php echo $msg; ?></strong>
                    <?php } ?>
                </div>
            <?php } ?>
            <!-- Msg Error -->

            <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                <div class="alert alert-danger">
                    <?php foreach ($this->flashMessenger()->getErrorMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong><?php echo $msg; ?></strong>
                    <?php } ?>
                </div>
            <?php } ?>

            <!-- Msg Warning -->

            <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                <div class="alert alert-warning">
                    <?php foreach ($this->flashMessenger()->getInfoMessages() as $msg) { ?>
                        <button type="button" class="close" data-dismiss="alert">×</button>    
                        <strong><?php echo $msg; ?></strong>
                    <?php } ?>
                </div>
            <?php } ?>

            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p style="text-align: center;">&copy; 2015 - <?php echo date('Y') ?> YouSelfie Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>