<div class="container">
    <div class="row" style="margin-top:20px">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
            <div role="form">
                <?php echo $this->form()->openTag($form); ?>
                <fieldset>
                    <hr class="colorgraph">
                    <div class="form-group form-group-cadastro">
                        <?php echo $this->formRow($form->get('email')); ?>
                    </div>
                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-6 col-sm-6 col-md-6">
                            <?php echo $this->formSubmit($form->get('recuperar')); ?>
                        </div>
                    </div>
                </fieldset>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>